# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f012711a8b7a67cd3fa6be65319a903d4981670ad981a959bba3d593ea55f3ceebcfc144d4fafc3a10cd41a6dabd2ddee60acf2b32be9f54fd623150f08a48af

test:
  secret_key_base: f8c833335f4f2fb5389b00fd7f4f68263afea9041cda6c3fe31c88d5f6eba9227687c038c45e230289ab077d441c42716cccb6c9bd809cfea3ee4527bfec4f4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
